// Star Wars characters data
export const characters = [
    { id: 1, name: "Luke Skywalker", gender: "male", homeworld: "Tatooine", species: "Human" },
    { id: 2, name: "Leia Organa", gender: "female", homeworld: "Alderaan", species: "Human" },
    { id: 3, name: "Han Solo", gender: "male", homeworld: "Corellia", species: "Human" },
    { id: 4, name: "Darth Vader", gender: "male", homeworld: "Tatooine", species: "Human" },
    { id: 5, name: "Obi-Wan Kenobi", gender: "male", homeworld: "Stewjon", species: "Human" },
    { id: 6, name: "Yoda", gender: "male", homeworld: "Unknown", species: "Yoda's species" },
    { id: 7, name: "C-3PO", gender: "n/a", homeworld: "Tatooine", species: "Droid" },
    { id: 8, name: "R2-D2", gender: "n/a", homeworld: "Naboo", species: "Droid" },
    { id: 9, name: "Chewbacca", gender: "male", homeworld: "Kashyyyk", species: "Wookiee" },
    { id: 10, name: "Lando Calrissian", gender: "male", homeworld: "Socorro", species: "Human" },
    { id: 11, name: "Boba Fett", gender: "male", homeworld: "Kamino", species: "Human (clone)" },
    { id: 12, name: "Emperor Palpatine", gender: "male", homeworld: "Naboo", species: "Human" },
    { id: 13, name: "Padmé Amidala", gender: "female", homeworld: "Naboo", species: "Human" },
    { id: 14, name: "Qui-Gon Jinn", gender: "male", homeworld: "Coruscant", species: "Human" },
    { id: 15, name: "Mace Windu", gender: "male", homeworld: "Haruun Kal", species: "Human" },
    { id: 16, name: "Count Dooku", gender: "male", homeworld: "Serenno", species: "Human" },
    { id: 17, name: "Darth Maul", gender: "male", homeworld: "Dathomir", species: "Dathomirian" },
    { id: 18, name: "Jabba the Hutt", gender: "male", homeworld: "Nal Hutta", species: "Hutt" },
    { id: 19, name: "Rey", gender: "female", homeworld: "Jakku", species: "Human" },
    { id: 20, name: "Finn", gender: "male", homeworld: "Unknown", species: "Human" },
    { id: 21, name: "Poe Dameron", gender: "male", homeworld: "Yavin IV", species: "Human" },
    { id: 22, name: "Kylo Ren", gender: "male", homeworld: "Chandrila", species: "Human" },
    { id: 23, name: "Rose Tico", gender: "female", homeworld: "Hays Minor", species: "Human" },
    { id: 24, name: "Jyn Erso", gender: "female", homeworld: "Vallt", species: "Human" },
    { id: 25, name: "Cassian Andor", gender: "male", homeworld: "Fest", species: "Human" },
    { id: 26, name: "K-2SO", gender: "n/a", homeworld: "Unknown", species: "Droid" },
    { id: 27, name: "Chirrut Îmwe", gender: "male", homeworld: "Jedha", species: "Human" },
    { id: 28, name: "Baze Malbus", gender: "male", homeworld: "Jedha", species: "Human" },
    { id: 29, name: "Saw Gerrera", gender: "male", homeworld: "Onderon", species: "Human" },
    { id: 30, name: "Orson Krennic", gender: "male", homeworld: "Lexrul", species: "Human" },
    { id: 31, name: "Grand Moff Tarkin", gender: "male", homeworld: "Eriadu", species: "Human" },
    { id: 32, name: "Greedo", gender: "male", homeworld: "Rodia", species: "Rodian" },
    { id: 33, name: "Wedge Antilles", gender: "male", homeworld: "Corellia", species: "Human" },
    { id: 34, name: "Biggs Darklighter", gender: "male", homeworld: "Tatooine", species: "Human" },
    { id: 35, name: "Admiral Ackbar", gender: "male", homeworld: "Mon Cala", species: "Mon Calamari" },
    { id: 36, name: "Nien Nunb", gender: "male", homeworld: "Sullust", species: "Sullustan" },
    { id: 37, name: "Maz Kanata", gender: "female", homeworld: "Takodana", species: "Unknown" },
    { id: 38, name: "General Hux", gender: "male", homeworld: "Arkanis", species: "Human" },
    { id: 39, name: "Captain Phasma", gender: "female", homeworld: "Parnassos", species: "Human" },
    { id: 40, name: "Lobot", gender: "male", homeworld: "Bespin", species: "Human" },
    { id: 41, name: "Din Djarin (The Mandalorian)", gender: "male", homeworld: "Unknown", species: "Human" },
    { id: 42, name: "Grogu (Baby Yoda)", gender: "male", homeworld: "Unknown", species: "Yoda's species" },
    { id: 43, name: "Cara Dune", gender: "female", homeworld: "Alderaan", species: "Human" },
    { id: 44, name: "Greef Karga", gender: "male", homeworld: "Unknown", species: "Human" },
    { id: 45, name: "Moff Gideon", gender: "male", homeworld: "Unknown", species: "Human" },
    { id: 46, name: "Bo-Katan Kryze", gender: "female", homeworld: "Mandalore", species: "Human" },
    { id: 47, name: "Ahsoka Tano", gender: "female", homeworld: "Shili", species: "Togruta" },
    { id: 48, name: "Fennec Shand", gender: "female", homeworld: "Unknown", species: "Human" },
    { id: 49, name: "Cobb Vanth", gender: "male", homeworld: "Unknown", species: "Human" },
    { id: 50, name: "Boba Fett (The Book of Boba Fett)", gender: "male", homeworld: "Kamino", species: "Human (clone)" },
    { id: 51, name: "Cad Bane", gender: "male", homeworld: "Duro", species: "Duro" },
    { id: 52, name: "Peli Motto", gender: "female", homeworld: "Unknown", species: "Human" },
    { id: 53, name: "IG-11", gender: "n/a", homeworld: "Unknown", species: "Droid" },
    { id: 54, name: "Kuiil", gender: "male", homeworld: "Unknown", species: "Ugnaught" },
    { id: 55, name: "The Armorer", gender: "female", homeworld: "Unknown", species: "Human" },
    { id: 56, name: "Koska Reeves", gender: "female", homeworld: "Unknown", species: "Human" },
    { id: 57, name: "Mayfeld", gender: "male", homeworld: "Unknown", species: "Human" },
    { id: 58, name: "Morgan Elsbeth", gender: "female", homeworld: "Unknown", species: "Human" },
    { id: 59, name: "Sabine Wren", gender: "female", homeworld: "Mandalore", species: "Human" },
    { id: 60, name: "Ezra Bridger", gender: "male", homeworld: "Lothal", species: "Human" },
    { id: 61, name: "Hera Syndulla", gender: "female", homeworld: "Ryloth", species: "Twi'lek" },
    { id: 62, name: "Chopper (C1-10P)", gender: "n/a", homeworld: "Unknown", species: "Droid" },
    { id: 63, name: "Grand Admiral Thrawn", gender: "male", homeworld: "Csilla", species: "Chiss" },
    { id: 64, name: "Baylan Skoll", gender: "male", homeworld: "Unknown", species: "Human" },
    { id: 65, name: "Shin Hati", gender: "female", homeworld: "Unknown", species: "Human" },
    { id: 66, name: "Reva (Third Sister)", gender: "female", homeworld: "Unknown", species: "Human" },
    { id: 67, name: "Obi-Wan Kenobi (series)", gender: "male", homeworld: "Stewjon", species: "Human" },
    { id: 68, name: "Tala Durith", gender: "female", homeworld: "Unknown", species: "Human" },
    { id: 69, name: "Ned-B", gender: "n/a", homeworld: "Unknown", species: "Droid" }
];

export const getCharacters = async () => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(characters);
        }, 1000);
    });
};
